### ISSUE TITLE
[Aquiraz/CE] Symfony/PHP Developer

### ISSUE THREAD

**Issue by clmadrazo** [CangaceirosDevels/vagas_de_emprego#1]
## Descrição da vaga

Venha fazer parte do time oowlish!
Na oowlish estamos à procura de desenvolvedores Symfony/PHP para juntar-se a nossa equipe!

## Local

Escritório, Ceará - Aquiraz

## Benefícios

- Trabalhar na “oowlish Mansion” 😉
- Uso de SCRUM, trabalhar numa das nossas squads.
- Ambiente de trabalho internacional, descontraído e cooperativo
- Trabalhar em produtos de sucesso internacional
- Salário
- Horário flexível

## Requisitos

**Obrigatórios:**
- Amplo conhecimento em PHP
- Ampla experiência em RESTFull APIs.
- HTML5, JS, CSS3
- Design patterns.
- Experiência em produtos mobile.
- Inglês básico (leitura/escrito)

**Desejáveis:**
- Conhecimentos de administração de servidores (AWS)
- Conhecimentos de Node.js

**Diferenciais:**
- Espanhol
- Backbone, require.js, Phonegap.

## Contratação

CLT

## Nossa empresa

oowlish é uma empresa de desenvolvimento dinâmico com sede no Porto Das Dunas. Nós adoramos móveis, web e excelente trabalho! Ajudamos às empresas a desenvolver e produzir seus produtos de mídia digital..

## Como se candidatar

Por favor envie um email para career@oowlish.com com seu CV anexado - enviar no assunto: Vaga PHP

**Comment by Pedro-Souza** [comment]
Beneficios: Salário
