### ISSUE TITLE
[Remoto / Fortaleza] Desenvolvedor(a) Python / Angular - Intmed Software

### ISSUE THREAD

**Issue by glairtonsantos** [CangaceirosDevels/vagas_de_emprego#104]
## Descrição da vaga

Desenvolvimento de sistemas web para área da médica utilizando Python/Django/Django REST Framework + JavaScript/Angular (Typescript, ES6)

## Local

Remoto, Fortaleza - CE

## Benefícios

- Home office parcial ou 100%
- Horário flexível
- Bônus semestral
- Trabalhar com projetos inovadores
- Custeio de cursos e participação em eventos

## Requisitos

**Obrigatórios:**
- Python/Django/Django REST Framework
- Angular (Typescript, ES6)
- API REST
- Git
- Experiência com integração de sistemas

**Diferenciais:**
- React, React Native e/ou Flutter
- Conhecimento deploy e configuração de aplicações
- Conhecimento em metodologias ágeis
- Experiência com SQL e banco Oracle
- Participação na comunidade open source

## Contratação

a combinar

## Nossa empresa

A **Intmed Software** é uma **HealthTech** que utiliza tecnologia para construir produtos inovadores e desenvolver soluções sob demanda para grandes players do mercado apoiadas pelo _know-how_ científico da sua equipe.

**Na Intmed cada pessoa possui as seguintes características:**

- Proatividade para assumir responsabilidades e resolver problemas.
- Capacidade de se auto-gerenciar e realizar as entregas.
- Ser participativ@ e ter como propósito melhorar a vida das pessoas! (Afinal, somos uma **HealthTech**!)

## Como se candidatar

Envie seu currículo para talentos@intmed.com.br com o título **[Seleção Dev/Python/Angular] - (Nome do candidat@)**

**Nosso processo de seleção consiste nas etapas:**

- Análise do currículo
- Desafio Django Rest Framework + Angular
- Entrevista

_Obs: É possível realizar apenas o **Backend** ou **Frontend** do desafio, se você for mais proficiente em um dos dois que merece destaque_

**Comment by arthurnunesc** [comment]
Vocês estão contratando estagiários?

**Comment by glairtonsantos** [comment]
> Vocês estão contratando estagiários?

Ainda não, mas provavelmente vai haver no futuro, assim que abrir uma vaga iremos compartilhar por aqui. Abs
